M48
; DRILL file {KiCad (6.0.1)} date Mon Feb  7 00:01:15 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-07T00:01:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.4803Y-1.6142
X2.4803Y-5.0787
X5.7087Y-1.6142
X5.7087Y-5.0787
T0
M30
